base: 'configs/icdar2015.yaml'
eval:
  benchmark: False
  model_path: 'outputs/'
  dataset:
    type: ICDAR2015Dataset
    args:
      data_path:
        - './datasets/ICDAR2015/test.txt'
      pre_processes:
        - type: ResizeImage
          args:
            min_len: 736
            max_len: 1280
            resize_text_polys: false
      transforms:
        - type: ToTensor
          args: {}
        - type: Normalize
          args:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
      filter_keys: [img_path, img_name, texts]  # 返回数据之前，从数据字典里删除的key
      ignore_tags: ['*', '###']
    loader:
      batch_size: 1
      shuffle: false
      pin_memory: True
      num_workers: 0
      collate_fn: ICDARCollectFN
arch:
  backbone:
    type: deformable_resnet18
    args:
      pretrained: false
  head:
    type: SegDetector
    args:
      inner_channels: 256
      k: 50
      adaptive: true
      smooth: true
      serial: false
post_process:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
    min_size: 3
metric:
  type: QuadMetric
  args:
    is_output_polygon: false